spring:
  main:
    banner-mode: log
  application:
   name: grpc-client

grpc:
  default-scheme: dns
  client:
    employeeService:
      address: ${APP_GRPC_SERVER_HOST:localhost}:9090 # If variable APP_GRPC_SERVER_HOST is set, use it. Otherwise the default is localhost
      negotiation-type: PLAINTEXT
      security:
        client-auth-enabled: false

logging:
  fluentd:
    host: ${APP_FLUENTD_HOST:localhost}
    port: ${APP_FLUENTD_PORT:24224}
