debug: true


grpc:
  default-scheme: dns
  client:
    employeeService:
      address: ${APP_GRPC_SERVER_HOST:localhost}:9090 # If variable APP_GRPC_SERVER_HOST is set, use it. Otherwise the default is localhost
      negotiation-type: PLAINTEXT
      security:
        client-auth-enabled: false
    