spring:
  main:
    banner-mode: log
  application:
   name: grpc-server
   
grpc:
  server:
    port: 9090
    security:
#      certificate-chain: classpath:/peer.pem
#      private-key: classpath:/pkcs8_key.pem
#      client-auth: require
      enabled: false
#      trust-cert-collection: classpath:/ca-chain.pem

logging:
  fluentd:
    host: ${APP_FLUENTD_HOST:localhost}
    port: ${APP_FLUENTD_PORT:24224}