spring:
  main:
    banner-mode: log
  application:
   name: grpc-server
  kafka:
   bootstrap-servers: ${APP_KAFKA_SERVERS:localhost:29092}
   producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

grpc:
  server:
    port: 9090
    security:
#      certificate-chain: classpath:/peer.pem
#      private-key: classpath:/pkcs8_key.pem
#      client-auth: require
      enabled: false
#      trust-cert-collection: classpath:/ca-chain.pem

logging:
  fluentd:
    host: ${APP_FLUENTD_HOST:localhost}
    port: ${APP_FLUENTD_PORT:24224}